language: python
python:
    - 2.7
    - 3.5
env:
    - MPI=mpich2
    - MPI=openmpi
before_install:
    - test $MPI == mpich2  && PACKAGES='mpich2 libmpich2-3 libmpich2-dev' || true
    - test $MPI == openmpi && PACKAGES='openmpi-bin openmpi-dev'          || true
    - sudo apt-get update -qq && sudo apt-get install -qq $PACKAGES
    - sudo apt-get install -qq python-numpy libblas-dev liblapack-dev
    - pip install mpi4py
    - pip install cvxopt -q
install:
    - python setup.py install
before_script:
    - MPIEXEC='mpiexec'
    - test $MPI == mpich2 && sudo hostname localhost || true
    - test $MPI == mpich2 && MPIEXEC='mpiexec -launcher fork' || true
script:
    - $MPIEXEC -n 5 python $PWD/bin/sines.py 
    - $MPIEXEC -n 5 python $PWD/bin/sines_quadprog.py 
